git hook_1

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,14 +4,18 @@
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
-echo "--- Running ES-Lint ---"
-#echo "--- Running Prettier ---"
+echo "--- Running ESLint ---"
 pnpm run lint
-#pmpm run prettier-fix
-if [[ "$?" == 0 ]]; then
-    git add -A
-    printf "\033[32m✅ ESLint Passed\033[0m\n"
-else
+if [[ "$?" != 0 ]]; then
     printf "\033[41m❌ ESLint Failed\033[0m\n"
     exit 1
 fi
+
+echo "--- Running Prettier ---"
+pnpm prettier --write src/*
+if [[ "$?" != 0 ]]; then
+    printf "\033[41m❌ Prettier Failed\033[0m\n"
+    exit 1
+fi
+
+printf "\033[32m✅ ESLint Passed and Prettier Formatted\033[0m\n"
